# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Conventional commits

on:
  push:
    branches: [heroku, master]
  pull_request:
    branches: [master]
    types: [opened, edited]

jobs:
  check-conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check commits
        uses: agenthunt/conventional-commit-checker-action@v1.0.0
