name: Node CI

on:
  push:
  pull_request:
    branches: [master]
    types: [opened, edited]

jobs:
  buildAndTest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install, build, test
        run: |
          npm install
          npm test
        #  - name: Prettier
        #    run: npm run prettier
        # Unclear ploblem with eslint
        #  - name: Eslint
        #    run: npm run eslint
        env:
          CI: true
